### ISSUE TITLE
App crashing while signup.

### ISSUE THREAD

**Issue by RohanMalik** [Airbitz/airbitz-core-java#1]
Hey, when I am trying to signup into Airbitz, at the time when we create password, when i create it and press next, the progress bar will rotate for a while and then it will crash. the error given is:

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'co.airbitz.core.CoreCurrency co.airbitz.core.Settings.currency()' on a null object reference
            at com.airbitz.activities.NavigationActivity$SetupFirstWalletTask.doInBackground(NavigationActivity.java:1874)
            at com.airbitz.activities.NavigationActivity$SetupFirstWalletTask.doInBackground(NavigationActivity.java:1855)

please help!!

**Comment by paullinator** [comment]
Hi Rohan. After you get the crash, can you please re enter the app, tap the logo 5 times, then choose to upload a log file. Enter your email in the text field so we know it's you. 

Afterwards email support@airbitz.co that you had done th upload. We'll take a look at it and see what's happening. 

Likely the app is having problems saving data to your phone possibly due to permissions or lack of space. Can you verify that your phone has sufficient storage? At least 20mb free?

If you have another device, please see if this one also has any issues. 

Thanks for letting us know about the problem

**Comment by aldefy** [comment]
Some additional info  + @RohanMalik , running it on OnePlus 2 with close to 30 gb of space , running marshmallow cm13 , and tried the same app on HTC phone , resulted in same.

**Comment by teneighty** [comment]
Hey @RohanMalik,

Are you building the app yourself or is this from a play store install? I can get you a new build which will be released in a few days that should fix the problem if you like.

**Comment by aldefy** [comment]
We are building it from source

**Comment by teneighty** [comment]
Great! Did you register with [developer.airbitz.co](developer.airbitz.co)? I just patched server side bug today with keys issued for developers that might cause this problem. Can you try creating a new account? I' just pushed some changes that should prevent NPEs like the one you are seeing in the future as well.

**Comment by aldefy** [comment]
How to register , app crashes no matter what we try , the link developer.airbitz.co takes us to barcode , what to do with it ?

**Comment by aldefy** [comment]
Unable to generate api key at this time. Please try again later.

**Comment by teneighty** [comment]
Please try again. We had a problem with our email server.

**Comment by RohanMalik** [comment]
we are unable to scan bar code. Is your server issue fixed?

**Comment by aldefy** [comment]
Unable to generate api key at this time. Please try again later.

**Comment by teneighty** [comment]
Please try the site again. I apologize for the problems. You might have hit a max username limit on our side. I've patched that and increased logging so I can't better understand problems in the future.

**Comment by teneighty** [comment]
@RohanMalik and @aldefy, were you able to register? Are you able to build and run the app now?
